//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.23 at 09:01:59 AM TRT 
//


package com.details.product;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.details.product package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.details.product
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllProductDetailsResponse }
     * 
     */
    public GetAllProductDetailsResponse createGetAllProductDetailsResponse() {
        return new GetAllProductDetailsResponse();
    }

    /**
     * Create an instance of {@link ProductDetails }
     * 
     */
    public ProductDetails createProductDetails() {
        return new ProductDetails();
    }

    /**
     * Create an instance of {@link GetProductDetailsResponse }
     * 
     */
    public GetProductDetailsResponse createGetProductDetailsResponse() {
        return new GetProductDetailsResponse();
    }

    /**
     * Create an instance of {@link PostProductDetailsRequest }
     * 
     */
    public PostProductDetailsRequest createPostProductDetailsRequest() {
        return new PostProductDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllProductDetailsRequest }
     * 
     */
    public GetAllProductDetailsRequest createGetAllProductDetailsRequest() {
        return new GetAllProductDetailsRequest();
    }

    /**
     * Create an instance of {@link PostProductDetailsResponse }
     * 
     */
    public PostProductDetailsResponse createPostProductDetailsResponse() {
        return new PostProductDetailsResponse();
    }

    /**
     * Create an instance of {@link GetProductDetailsRequest }
     * 
     */
    public GetProductDetailsRequest createGetProductDetailsRequest() {
        return new GetProductDetailsRequest();
    }

}
